
project_id = "dermbucktbegnbkjzobs"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[storage]
enabled = true

[edge-functions]
enabled = true

[functions]
[functions.calculate-payment-amount]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.create-direct-payment-intent]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.send-conference-confirmation]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.store-registration]
verify_jwt = false

[functions.verify-email-domain]
verify_jwt = false

[functions.verify-email-token]
verify_jwt = false

[functions.send-next-steps-email]
verify_jwt = false
