
project_id = "dermbucktbegnbkjzobs"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[storage]
enabled = true

[auth]
enabled = true

[functions]
enabled = true

[functions.validate-coupon-code]
verify_jwt = false
