[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true # Added force parameter to ensure all routes are handled

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'; default-src 'self'; script-src 'self' https://js.stripe.com https://api.stripe.com https://*.supabase.co https://cdn.gpteng.co 'unsafe-inline'; connect-src 'self' https://*.supabase.co https://api.stripe.com https://*.amazonaws.com wss://*.supabase.co https://*.stripe.com https://pay.google.com https://ingesteer.services-prod.nsvcs.net https://fonts.googleapis.com https://fonts.gstatic.com; frame-src https://js.stripe.com https://hooks.stripe.com https://pay.google.com; img-src 'self' data: https://*.amazonaws.com https://*.supabase.co https://dermbucktbegnbkjzobs.supabase.co https://storage.googleapis.com https://images.unsplash.com; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; font-src 'self' https://fonts.gstatic.com;"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "authorization, x-client-info, apikey, content-type"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables set in the Netlify UI take precedence over these
[context.production.environment]
  # These are placeholder comments - actual values should be set in Netlify UI
  # RESEND_API_KEY = ""
  # SUPABASE_URL = ""
  # SUPABASE_SERVICE_ROLE_KEY = ""
