// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dermbucktbegnbkjzobs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlcm1idWNrdGJlZ25ia2p6b2JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5MjExOTgsImV4cCI6MjA1MzQ5NzE5OH0.J7OVreQMRDIuYbkt3oHGqp1A7oX09t9NCdpKbFJKNHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);